name: progressivis-environment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - nodejs
  - pkgconfig
  - pip
  - numpy
  - cython
  - pip:
    - install -e .
    - install -e progressivis_nb_widgets

    