name: progressivis-environment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - nodejs
  - pkgconfig
  - pip
  - numpy
  - cython
  - voila
  - ipydatawidgets
  - pip:
    - -e ..
    - -e ../widgets



    